name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh ${SERVER_USER}@${SERVER_HOST} << 'EOF'
            cd ${DEPLOY_PATH}
            
            # Pull latest code
            git pull origin main
            
            # Pull latest Docker image
            docker-compose pull
            
            # Stop old containers
            docker-compose down
            
            # Start new containers
            docker-compose up -d
            
            # Clean up old images
            docker image prune -f
            
            # Check health
            sleep 10
            curl -f http://localhost:3000/health || exit 1
          EOF

      - name: Verify deployment
        run: |
          curl -f https://${{ secrets.DOMAIN_NAME }}/health || exit 1
          echo "✅ Deployment successful!"

      - name: Notify success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: 'Deployment',
              description: 'Deployment successful!'
            })

      - name: Notify failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'failure',
              context: 'Deployment',
              description: 'Deployment failed!'
            })

      - name: Rollback on failure
        if: failure()
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh ${SERVER_USER}@${SERVER_HOST} << 'EOF'
            cd ${DEPLOY_PATH}
            docker-compose down
            docker-compose up -d masup-frontend:previous
          EOF
